import { createSlice, configureStore } from "@reduxjs/toolkit";

const sliceGame = createSlice({
    name: 'game',
    initialState: { //Initial Game's datas 
        dice: 1,
        gameOn: false,
        winner: 0,
        players: [
            {
                id: 1,
                turn: true,
                current: 0,
                global: 0
            },
            {
                id: 2,
                turn: false,
                current: 0,
                global: 0
            }
        ]
    },
    reducers: {
        startNewGame: (state) => { //start New game initialising datas to default except for players' turn
            state.gameOn = !state.gameOn
            state.winner = 0
            state.dice = 1
            state.players.forEach(player => {
                player.current = 0
                player.global = 0
            })
        },
        rollDice: (state) => { // simulate dice roll and applying modification to data
            const dice = Math.ceil(Math.random() * 6) //simulate dice roll
            state.dice = dice //changing dice value
            if (dice > 1) { // if it's upper to 1 change current score depending on which player rolled the dice
                state.players.forEach(player => {
                    if (player.turn) {
                        player.current += dice
                    }
                })
            } else { // Else change current  score to Zero and change player turn
                state.players.forEach(player => {
                    if (player.turn) {
                        player.current = 0
                    }
                })
                sliceGame.caseReducers.switchTurn(state)
            }
        },
        holdDice: (state) => { // Hold dice to save current score to global, or end the game if player reached 100pts
            state.players.forEach(player => {
                if (player.turn) {//save the current score
                    player.global += player.current
                    player.current = 0
                }
                if (player.global >= 100) { //end the game
                    state.gameOn = !state.gameOn
                    state.winner = player.id
                }
            })

            sliceGame.caseReducers.switchTurn(state) //switch player

        },
        switchTurn: (state) => { //reducer used internally to switch player
            state.players.forEach(player => player.turn = !player.turn)
        },
    }
})

//exports create-Actions generated by redux-toolkit
export const { rollDice, holdDice, startNewGame } = sliceGame.actions

//exports stores
export const store = configureStore({
    reducer: {
        game: sliceGame.reducer
    }
})